---
name: Lint code

on: [push, pull_request]

env:
  # Pylint does not work via pre-commit in CI
  SKIP: pylint

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1
    - name: GitHub Action for pylint
      uses: cclauss/GitHub-Action-for-pylint@0.7.0
